test cases and additional documentation updates
camaraproject/ConnectivityInsights pull request #66
Opened 2024-08-08 21:04 UTC by maheshc01

updated to include positive test cases as per CAMARA guidelines.
Also made few updates to documentation.

2024-08-08 21:11 UTC, maheshc01 commented
@Kevsy fro review and merge.

2024-08-09 10:50 UTC, Kevsy commented on CHANGELOG.md
> +* Connecitvity Insights API
```suggestion
* Connectivity Insights API
```

2024-08-09 10:52 UTC, Kevsy commented on CHANGELOG.md
> +- [r1.1]
```suggestion
- [r1.1 -  rc]
```

2024-08-09 10:53 UTC, Kevsy commented on CHANGELOG.md
> +* Identity and Consent Management v0.2.0
```suggestion
* Identity and Consent Management v0.2.0-rc.1
```

2024-08-09 11:05 UTC, Kevsy commented on CHANGELOG.md
> +  - [View it on ReDoc]
```suggestion
  - View it on ReDoc:
    - [connectivity-insights.yaml](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/ConnectivityInsights/r1.1/code/API_definitions/connectivity-insights.yaml&nocors)
    
    - [application-profiles.yaml](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/ConnectivityInsights/r1.1/code/API_definitions/application-profiles.yaml&nocors)
```

2024-08-09 11:07 UTC, Kevsy commented on CHANGELOG.md
> +  - [View it on Swagger Editor]
```suggestion
  - [View it on Swagger Editor]
    - [connectivity-insights.yaml]((https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/ConnectivityInsights/r1.1/code/API_definitions/connectivity-insights.yaml))
      - [application-profiles.yaml]((https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/ConnectivityInsights/r1.1/code/API_definitions/application-profiles.yaml))
```

2024-08-09 11:10 UTC, Kevsy commented on CHANGELOG.md
> +  - OpenAPI [YAML spec file]
```suggestion
  - OpenAPI
    -  [connectivity-insights.yaml](https://raw.githubusercontent.com/camaraproject/ConnectivityInsights/r1.1/code/API_definitions/connectivity-insights.yaml)
    -  [application-profiles.yaml](https://raw.githubusercontent.com/camaraproject/ConnectivityInsights/r1.1/code/API_definitions/application-profiles.yaml)
```

2024-08-09 11:11 UTC, Kevsy commented on code/API_definitions/application-profiles.yaml
> +    information about their application which would be relavant for network/
```suggestion
    information about their application which would be relevant for network/
```

2024-08-09 11:18 UTC, Kevsy commented on documentation/API_documentation/ConnecitvityInsights-SequenceDiagram.png
The filename has a typo (Connecitvity -> Connectivity)

2024-08-09 11:19 UTC, Kevsy requested changes
Looks good other than the comments provided (with suggested fixes)

2024-08-09 15:17 UTC, Kevsy approved these changes

2024-08-09 15:17 UTC, merged