Update CAMARA Connectivity Insights API.yaml
camaraproject/ConnectivityInsights pull request #7
Opened 2023-12-06 16:13 UTC by Kevsy

Fixes #6

#### What type of PR is this?

Add one of the following kinds:
* bug
* correction
* enhancement/feature
* cleanup
* documentation
* subproject management
* tests

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for reviewers:

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

2023-12-06 16:36 UTC, hdamker requested changes
Several comments:

* There is no need to align the API basepath with the mailing list acronym 
* Instead you should maybe even avoid an acronym if possible and think about a more developer friendly basePath
* Please don't change the version number with every PR which will go into main branch. Use something like 0.1.0-wip until you do a release in the sub project (there is currently no release with has used 0.1.0 as API version number. If you want to distinct the current work in progress from the initial contribution then 0.2.0-wip could make sense

2023-12-06 16:38 UTC, hdamker commented
> Several comments:
> 
> * There is no need to align the API basepath with the mailing list acronym
> * Instead you should maybe even avoid an acronym if possible and think about a more developer friendly basePath
> * Please don't change the version number with every PR which will go into main branch. Use something like 0.1.0-wip until you do a release in the sub project (there is currently no release with has used 0.1.0 as API version number. If you wan't to distinct the current work in progress from the initial contribution then 0.2.0-wip could make sense

2023-12-06 17:04 UTC, hdamker commented
> * egarding the basepath: I can't find any guidance in [API Design Guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md) regarding this - and several other APIs have these abbreviated ID's in their basepaths (`/qod/` , `/eds/`, `/ti/`, `/dvi/`) .  I'm happy to change but would be good to get a consistent position across APIs - I don't recall it being discussed in Commonalities but can raise  a Discussion if not.

See my comment in the issue. There you find the good examples, you picked the bad ones :-)

The guidelines say:

> URI with lowercase and hyphens. URIs must be "human readable" to facilitate identification of the offered resources. Lowercase words and hyphenation (kebab-case) help achieve this best practice. For example: /customer-segments

2023-12-12 17:19 UTC, Kevsy commented
Thanks @hdamker , commit added to reflect 'connectivity-insights' as basepath.

2023-12-12 21:57 UTC, maheshc01 approved these changes

2023-12-13 11:50 UTC, Kevsy commented
@hdamker please can you confirm the [new commit](https://github.com/camaraproject/ConnectivityInsights/pull/7/files) meets your requested changes..?

- basepath changed to /connectivity-insights/ 
- version change to 0.1.0-wip

Many thanks!

2023-12-18 14:49 UTC, Kevsy commented
Superseded by PR 15

2023-12-18 14:49 UTC, closed without merging

2023-12-18 17:53 UTC, hdamker commented
@Kevsy  I'm getting currently too many notifications from GitHub. Yes, the commit would have had met my request. Sorry that it is too late now and you had to solve it with a new PR.

2023-12-19 11:31 UTC, Kevsy commented
@hdamker understood, and no problem at all! Thanks for the good feedback :)